California:
  enabled: true,
  credit_score_threshold: 4

  Counties:
    Alameda:
      enabled: true,
      credit_score_threshold: 8
    Butte:
    Contra Costa:
    El Dorado:
    Fresno:
    Humboldt:
    Kern:
    Los Angeles:
    Madera:
    Marin:
    Mendocino:
    Merced:
    Monterey:
    Napa:
    Nevada:
    Orange:
    Riverside:
    Sacramento:
    San Bernardino:
    San Benito:
    San Diego:
    San Francisco:
    San Joaquin:
    San Luis Obispo:
    San Mateo:
    Santa Clara:
    Santa Cruz:
    Shasta:
    Solano:
    Sonoma:
    Stanislaus:
    Sutter:
    Tulare:
    Ventura:
    Yolo:

Florida:
    enabled: true,
    credit_score_threshold: 5
